spring:
  application:
    name: Influx-API
  profiles:
    active: prod

  influxdb:
    token: PN9kPT8ZwlyJwj9tCNSwe9jj4MIdc0SATVq1cpHhqDN4-tfkiQIm-BkyKJlCDPolrDdei63JSan1TN_QejUPUQ==
    org: HA
    bucket: homeassistant

mqtt:
  username: jongsik2
  password: js102938@