spring:
  application:
    name: Influx-API

  influxdb:
    url: http://192.168.0.100:8086
    username: homeassistant
    password: homeassistant
    database: homeassistant

mqtt:
  url: tcp://192.168.0.100:1883
  username: jongsik2
  password: jongsik2